# Generated by Django 5.2.3 on 2025-06-13 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sociedade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Membro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(choices=[('Presisdente', 'Presidente'), ('Vice-Presidente', 'Vice-Presidente'), ('1º Secretário', '1ºSecretário'), ('2º Secretário', '2º Secretário'), ('Membro', 'Membro')], max_length=50)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sociedade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sociedades.sociedade')),
            ],
        ),
    ]
